[package]
name = "litebox-platform-linux-userland"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2.169", default-features = false }
litebox = { path = "../litebox/", version = "0.1.0" }
nix = { version = "0.29.0", default-features = false, features = ["fs", "ioctl"] }
